version: '2'
services:
    whereq_realtor_ca-app:
        image: whereq_realtor_ca
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://whereq_realtor_ca-mysql:3306/whereq_realtor_ca?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    whereq_realtor_ca-mysql:
        extends:
            file: mysql.yml
            service: whereq_realtor_ca-mysql
